 apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  template:
    metadata:
     name: webserver
     labels:
      app.kubernetes.io/name: nginx
    spec:
     containers:
      - name: webserver 
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"