apiVersion: v1
kind: Service
metadata:
 name: webserver
 labels:
  app.kubernetes.io/name: webservice
 annotations:
  service.beta.kubernetes.io/aws-load-balancer-security-groups: "webserver-service-security-group"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP