apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
   app.kubernetes.io/name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
     app.kubernetes.io/name: nginx
  template:
    metadata:
     name: webserver
     labels:
      app.kubernetes.io/name: nginx
    spec:
     containers:
      - name: webserver
        image: nginx:1.14.2
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            protocol: TCP