apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 2048-game

commonLabels:
 app.kubernetes.io/name: 2048-game

images:
- name: nginx
  newName: alexwhen/docker-2048

replacements:
- source:
   kind: Service
   fieldPath: metadata.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-security-groups\:\"sg\"]
  targets:
  - select:
     fieldPaths: metadata.annotations.[service.beta.kubernetes.io/aws-load-balancer-security-groups]

resources:
- webserver-deployment.yaml
