apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: webserver
  labels:
    app.kubernetes.io/name: webserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
  replicas: 4
  template:
    metadata:
      name: webserver
      labels:
        app.kubernetes.io/name: webserver
      namespace: webserver
    spec:
      containers:
        - name: webserver
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: webserver
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-security-groups: "webserver-service-security-group"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: webserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
